version: '3'
services:
  service:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    image: react_blog:service
    ports:
      - 9002:9002
    restart: on-failure
    environment:
      MYSQL_HOST: 172.17.0.1
      MYSQL_USER: root
      MYSQL_PASSWORD: mysql_8023.
    volumes:
      - ../article:/usr/src/app/article
    networks:
      - react_blog
    container_name: react_blog_service
networks:
  react_blog:
