version: '3'
services:
  service:
    build: 
      - context: ../
      - dockerfile: ./docker/Dockerfile
    image: react_blog:service
    ports:
      - 9002:9002
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_USER=root
      - MYSQL_PASSWORD=8023
      # - MYSQL_DATABASE=react_blog
    network_mode: host
    container_name: react_blog_service
  