version: '3'
services:
  # blog:
  #   build: ./blog
  #   image: react_blog:blog
  #   ports:
  #     - 9000:9000
  #   networks: 
  #     - react_blog_net
  #   container_name: blog
  admin:
    build: ./admin
    image: react_blog:admin
    ports: 
      - 9001:80
    volumes: 
      - ./admin/dist/src:/www
      - ./admin/dist/config/nginx.conf:/etc/nginx/conf.d/nginx.conf
    networks: 
      - my-net
    container_name: admin
  service:
    build: ./service
    image: react_blog:service
    ports:
      - 9002:9002
    environment:
      - MYSQL_HOST=host.docker.internal
      - MYSQL_USER=root
      - MYSQL_PASSWORD=8023
      - HOST=0.0.0.0
    networks: 
      - my-net
    container_name: webapp
networks: 
  my-net:
