version: '3'
services:
  blog:
    build: ./blog
    image: react_blog:blog
    ports:
      - 9000:9000
    networks: 
      - react_blog_net
    container_name: blog
  # admin:
  #   build: ./admin
  #   image: react_blog:admin
  #   ports: 
  #     - 9001:80
  #   networks: 
  #     - react_blog_net
  #   container_name: admin
  service:
    build: ./service
    image: react_blog:service
    ports:
      - 9002:9002
    environment:
      - MYSQL_HOST=172.0.17.1
      - MYSQL_USER=root
      - MYSQL_PASSWORD=8023
    # network_mode: host
    networks: 
      - react_blog_net
    container_name: service
networks: 
  react_blog_net:
